// Каталог витрины.
// priceKzt: розничная цена из каталога Казахстана в тенге (число без пробелов).
// На сайте цена показывается в рублях: priceKzt × kztToRub (см. config.js), со сноской.
// img: фото товара (из каталога), папка shop/img.
// sku: артикул из каталога. Попадает в заявку, чтобы было проще оформить заказ.
// Цены и артикулы сверены с каталогом РК rukz-katalog-2026 (файл от 16.09.2026).
//
// hit:  true = товар показывается на первой странице (по 5 в каждом разделе), остальные по кнопке «Все товары раздела»
// cat:  health | beauty | home
// tags: energy, immunity, gut, skin, shape, hair, clean, water, air, family
//       (по ним квиз подбирает товары и программы)

window.SHOP_PRODUCTS = [
  // ---------- Здоровье ----------
  { id: "daily", hit: true, cat: "health", img: "img/daily.webp", brand: "Nutrilite", name: "Дэйли, витамины и минералы",
    size: "45 таблеток", sku: "125166", priceKzt: 9970, tags: ["energy", "immunity", "family"],
    desc: "Витамины и минералы на каждый день для взрослых." },
  { id: "omega", hit: true, cat: "health", img: "img/omega.webp", brand: "Nutrilite", name: "Омега-3 Комплекс Плюс",
    size: "60 капсул", sku: "126136", priceKzt: 23055, tags: ["energy", "skin", "family"],
    desc: "Дополнительный источник омега-3 (ЭПК и ДГК) из рыбьего жира и масла семян чиа." },
  { id: "vitd", hit: true, cat: "health", img: "img/vitd.webp", brand: "Nutrilite", name: "Витамин D",
    size: "90 таблеток", sku: "119797", priceKzt: 11450, tags: ["immunity", "family"],
    desc: "Поддержка в сезон, когда солнца мало." },
  { id: "vitc", cat: "health", img: "img/vitc.webp", brand: "Nutrilite", name: "Витамин С плюс",
    size: "60 таблеток", sku: "109741", priceKzt: 11370, tags: ["immunity"],
    desc: "Витамин С с концентратом вишни ацеролы, высвобождается постепенно в течение 8 часов." },
  { id: "calmag", cat: "health", img: "img/calmag.webp", brand: "Nutrilite", name: "Кальций, магний, витамин D комплекс",
    size: "90 таблеток", sku: "110605", priceKzt: 8325, tags: ["family", "energy"],
    desc: "Минералы для ежедневного рациона." },
  { id: "protein", hit: true, cat: "health", img: "img/protein.webp", brand: "Nutrilite", name: "Протеиновый порошок",
    size: "450 г", sku: "110415", priceKzt: 21800, tags: ["shape", "energy"],
    desc: "Растительный белок. Добавляйте в каши, смузи, выпечку." },
  { id: "probiotic", hit: true, cat: "health", img: "img/probiotic.webp", brand: "Nutrilite", name: "Balance Within Пробиотик",
    size: "30 саше", sku: "120571", priceKzt: 22200, tags: ["immunity", "shape", "gut"],
    desc: "Полезные бактерии для баланса микрофлоры кишечника." },
  { id: "fiber", cat: "health", img: "img/fiber.webp", brand: "Nutrilite", name: "Жевательные таблетки Смесь пищевых волокон",
    size: "30 таблеток", sku: "104283", priceKzt: 11220, tags: ["shape", "gut"],
    desc: "Растворимые и нерастворимые пищевые волокна из 13 источников. Со вкусом апельсинового крема." },
  { id: "inulin", cat: "health", img: "img/inulin.webp", brand: "Nutrilite", name: "Смесь пищевых волокон с инулином",
    size: "30 пакетиков по 6 г", sku: "102736", priceKzt: 21060, tags: ["gut"],
    desc: "Пищевые волокна и инулин из корня цикория. Напиток: 1 пакетик в день." },
  { id: "liver", cat: "health", img: "img/liver.webp", brand: "Nutrilite", name: "Печень Актив",
    size: "60 таблеток", sku: "100352", priceKzt: 13990, tags: ["gut"],
    desc: "Экстракты расторопши и одуванчика, витамины группы B. 1 таблетка в сутки." },
  { id: "garlic", cat: "health", img: "img/garlic.webp", brand: "Nutrilite", name: "Чеснок",
    size: "120 таблеток", sku: "100566", priceKzt: 14200, tags: ["immunity", "gut"],
    desc: "Концентрат чеснока в таблетках, без запаха." },
  { id: "doublex", cat: "health", img: "img/doublex.webp", brand: "Nutrilite", name: "Double X, витамины, минералы и фитонутриенты",
    size: "упаковка на 31 день", sku: "121576", priceKzt: 29080, tags: ["energy", "immunity"],
    desc: "Комплекс витаминов, минералов и фитонутриентов на месяц." },
  { id: "xsmag", cat: "health", img: "img/xsmag.webp", brand: "XS", name: "Магний, вкус лимона",
    size: "30 стик-пакетиков", sku: "121062", priceKzt: 7775, tags: ["energy"],
    desc: "Магний в удобных стиках для напитка. Без сахара." },
  { id: "appetite", cat: "health", img: "img/appetite.webp", brand: "Nutrilite", name: "Контроль аппетита",
    size: "30 саше", sku: "119792", priceKzt: 20575, tags: ["shape", "gut"],
    desc: "Помощник для тех, кто следит за питанием и перекусами." },
  { id: "echinacea", cat: "health", img: "img/echinacea.webp", brand: "Nutrilite", name: "Эхинацея плюс",
    size: "120 таблеток", sku: "5986", priceKzt: 23560, tags: ["immunity"],
    desc: "Экстракты двух видов эхинацеи для поддержки защитных функций организма." },
  { id: "zinc", cat: "health", img: "img/zinc.webp", brand: "Nutrilite", name: "Цинк + селен",
    size: "30 саше", sku: "126811", priceKzt: 13880, tags: ["immunity", "skin", "hair"],
    desc: "Цинк и селен с витамином С. Не нужно растворять и запивать, апельсиновый вкус." },
  { id: "bdlight", cat: "health", img: "img/bdlight.webp", brand: "Nutrilite", name: "Набор Body Detox Light",
    size: "3 продукта", sku: "313447", priceKzt: 54008, tags: ["gut", "shape"],
    desc: "Смесь пищевых волокон с инулином, Печень Актив и Протеиновый порошок. Базовый набор на 3 недели." },

  { id: "daily90", cat: "health", img: "img/daily.webp", brand: "Nutrilite", name: "Дэйли, витамины и минералы, большая упаковка",
    size: "90 таблеток", sku: "125167", priceKzt: 18645, tags: ["energy", "immunity", "family"],
    desc: "Та же формула, что у Дэйли 45, на 3 месяца приёма. В пересчёте на таблетку выгоднее." },
  { id: "kidsmulti", cat: "health", img: "img/kidsmulti.webp", brand: "Nutrilite", name: "Детские жевательные таблетки с мультивитаминами",
    size: "120 таблеток", sku: "100930", priceKzt: 13625, tags: ["family", "immunity"],
    desc: "Витамины и минералы для роста и учёбы, с концентратами экзотических фруктов. Для детей с 4 лет." },

  // ---------- Красота ----------
  { id: "cleanser", cat: "beauty", img: "img/cleanser.webp", brand: "Artistry Skin Nutrition", name: "Увлажняющий очищающий мусс для умывания",
    size: "145 мл", sku: "123793", priceKzt: 17920, tags: ["skin"],
    desc: "Мягко очищает, не пересушивает. Для ежедневного ухода утром и вечером." },
  { id: "toner", cat: "beauty", img: "img/toner.webp", brand: "Artistry Skin Nutrition", name: "Увлажняющий смягчающий тоник для лица",
    size: "200 мл", sku: "123795", priceKzt: 14260, tags: ["skin"],
    desc: "Восстанавливает баланс кожи после умывания." },
  { id: "cream", hit: true, cat: "beauty", img: "img/cream.webp", brand: "Artistry Skin Nutrition", name: "Увлажняющий крем-гель для лица",
    size: "50 г", sku: "123798", priceKzt: 24025, tags: ["skin"],
    desc: "Лёгкая текстура, интенсивное увлажнение." },
  { id: "serum", hit: true, cat: "beauty", img: "img/serum.webp", brand: "Artistry Skin Nutrition", name: "Сыворотка с витамином C и гиалуроновой кислотой",
    size: "12 мл", sku: "125517", priceKzt: 34955, tags: ["skin"],
    desc: "Для более ровного тона и сияния кожи." },
  { id: "shampoo", hit: true, cat: "beauty", img: "img/shampoo.webp", brand: "Satinique", name: "Шампунь для гладкости волос",
    size: "280 мл", sku: "126449", priceKzt: 8495, tags: ["hair", "family"],
    desc: "С экстрактами киноа и баобаба. Мягко очищает и облегчает расчёсывание." },
  { id: "conditioner", cat: "beauty", img: "img/conditioner.webp", brand: "Satinique", name: "Кондиционер для гладкости волос",
    size: "280 мл", sku: "126451", priceKzt: 7915, tags: ["hair"],
    desc: "Увлажнение и гладкость без утяжеления." },
  { id: "handcream", cat: "beauty", img: "img/handcream.webp", brand: "g&h", name: "Питательный крем для рук",
    size: "75 мл", sku: "125902", priceKzt: 6155, tags: ["skin", "family"],
    desc: "Питательный крем без липкости." },
  { id: "hairmask", cat: "beauty", img: "img/hairmask.webp", brand: "Satinique", name: "Маска для интенсивного восстановления волос",
    size: "250 мл", sku: "126465", priceKzt: 14855, tags: ["hair"],
    desc: "Для ослабленных, повреждённых и окрашенных волос. Укрепляет и делает волосы гладкими." },
  { id: "hairoil", cat: "beauty", img: "img/hairoil.webp", brand: "Satinique", name: "Интенсивно восстанавливающая сыворотка-масло для волос",
    size: "100 мл", sku: "126467", priceKzt: 16260, tags: ["hair"],
    desc: "Запечатывает кутикулу, убирает пушистость, восстанавливает секущиеся кончики." },
  { id: "showergel", hit: true, cat: "beauty", img: "img/showergel.webp", brand: "g&h", name: "Питательный гель для душа",
    size: "400 мл", sku: "125890", priceKzt: 6960, tags: ["skin", "family"],
    desc: "Мягко очищает и питает кожу. Без сульфатных ПАВ, красителей, парабенов и спирта." },
  { id: "bodylotion", cat: "beauty", img: "img/bodylotion.webp", brand: "g&h", name: "Питательный лосьон для тела",
    size: "400 мл", sku: "125891", priceKzt: 10590, tags: ["skin", "family"],
    desc: "Питает сухую кожу, быстро впитывается, не липнет." },
  { id: "toothpaste", hit: true, cat: "beauty", img: "img/toothpaste.webp", brand: "Glister", name: "Многофункциональная зубная паста",
    size: "200 г", sku: "124106", priceKzt: 4200, tags: ["family"],
    desc: "Защищает эмаль, уменьшает налёт, освежает дыхание. Большой тюбик надолго." },

  { id: "pastetravel", cat: "beauty", img: "img/pastetravel.webp", brand: "Glister", name: "Многофункциональная зубная паста, дорожный формат",
    size: "50 г", sku: "124107", priceKzt: 1850, tags: ["family"],
    desc: "Та же формула, что в большом тюбике, в формате для поездок и сумки." },
  { id: "soap250", cat: "beauty", img: "img/soap250.webp", brand: "g&h", name: "Питательное ухаживающее мыло для тела и лица",
    size: "250 г", sku: "125913", priceKzt: 5435, tags: ["skin", "family"],
    desc: "Кусковое мыло деликатно очищает кожу, делает её мягкой. Без сульфатных ПАВ, красителей, парабенов и спирта." },
  { id: "soap6", cat: "beauty", img: "img/soap6.webp", brand: "g&h", name: "Мультифункциональное мыло для очищения и защиты кожи, набор",
    size: "6 × 150 г", sku: "125897", priceKzt: 14660, tags: ["skin", "family"],
    desc: "Мягкое кусковое мыло с пребиотиками, розмарином и экстрактом зелёного чая Nutrilite. Хватает на всю семью надолго." },
  { id: "brushsoft", cat: "beauty", img: "img/brush.webp", brand: "Glister", name: "Многофункциональная зубная щётка, мягкая",
    size: "4 шт.", sku: "124109", priceKzt: 7445, tags: ["family"],
    desc: "Щётка с мягкой щетиной и технологией In-mold: больше нитей на головке для чистки труднодоступных мест." },
  { id: "brushmed", cat: "beauty", img: "img/brush.webp", brand: "Glister", name: "Многофункциональная зубная щётка, средняя",
    size: "4 шт.", sku: "124110", priceKzt: 7445, tags: ["family"],
    desc: "Щётка со средней жёсткостью щетины и технологией In-mold: больше нитей на головке для чистки труднодоступных мест." },
  { id: "rinse", cat: "beauty", img: "img/rinse.webp", brand: "Glister", name: "Многофункциональный ополаскиватель для полости рта",
    size: "72 мл, концентрат", sku: "124108", priceKzt: 7645, tags: ["family"],
    desc: "Концентрат без спирта: уничтожает бактерии, которые могут вызывать неприятный запах, и освежает дыхание." },
  { id: "spray", cat: "beauty", img: "img/spray.webp", brand: "Glister", name: "Спрей-освежитель для полости рта с запахом мяты",
    size: "14 мл", sku: "124111", priceKzt: 3140, tags: ["family"],
    desc: "Мгновенно освежает дыхание. Компактный флакон на 223 распыления можно взять с собой." },

  // ---------- Для дома ----------
  { id: "loc", hit: true, cat: "home", img: "img/loc.webp", brand: "Amway Home", name: "L.O.C. Многофункциональное чистящее средство",
    size: "1 л", sku: "0001", priceKzt: 5900, tags: ["clean", "family"],
    desc: "Концентрат: из 1 л получается 20 флаконов готового средства." },
  { id: "sa8", hit: true, cat: "home", img: "img/sa8.webp", brand: "Amway Home", name: "SA8 Premium, стиральный порошок концентрированный",
    size: "3 кг", sku: "109849", priceKzt: 26900, tags: ["clean", "family"],
    desc: "Малая дозировка, эффективен при низких температурах." },
  { id: "dish", hit: true, cat: "home", img: "img/dish.webp", brand: "Amway Home", name: "Dish Drops, жидкость для мытья посуды",
    size: "1 л", sku: "110488", priceKzt: 6430, tags: ["clean"],
    desc: "Концентрат: из 1 л получается 8 флаконов по 500 мл." },
  { id: "glass", cat: "home", img: "img/glass.webp", brand: "Amway Home", name: "L.O.C. Жидкость для мытья стёкол",
    size: "500 мл", sku: "117080", priceKzt: 4905, tags: ["clean"],
    desc: "Для окон, зеркал и глянцевых поверхностей. Режимы «распыление» и «пена»." },
  { id: "espring", hit: true, cat: "home", img: "img/espring.webp", brand: "eSpring", name: "Система очистки воды",
    size: "с подключением к основному крану", sku: "122940", priceKzt: 702270, tags: ["water", "family"],
    desc: "Чистая вода прямо из-под крана. Консультант поможет выбрать вариант установки." },
  { id: "atmosphere", hit: true, cat: "home", img: "img/atmosphere.webp", brand: "Atmosphere", name: "Atmosphere Mini, очиститель воздуха",
    size: "фильтр 3 в 1", sku: "124746", priceKzt: 488540, tags: ["air", "family"],
    desc: "Предфильтр, HEPA и угольный фильтр: задерживает мелкие частицы и запахи." },
  { id: "espringcart", cat: "home", img: "img/espringcart.webp", brand: "eSpring", name: "Угольный фильтр e3, сменный картридж с предфильтром",
    size: "до 5 000 л в год", sku: "122943", priceKzt: 107530, tags: ["water", "family"],
    desc: "Сменный картридж для новой системы eSpring: меняется раз в год, предфильтр уже внутри." },
  { id: "oven", cat: "home", img: "img/oven.webp", brand: "Amway", name: "Чистящее средство-гель для духовых шкафов",
    size: "500 мл", sku: "0014", priceKzt: 5405, tags: ["clean"],
    desc: "За 30 минут растворяет жир и пригоревшие остатки. Удобно наносится прилагаемой кисточкой." }
];

// Готовые программы: набор товаров под задачу.
// Цена считается автоматически как сумма товаров из items.
window.SHOP_PROGRAMS = [
  // ---------- Программы здоровья с сопровождением (coached: true) ----------
  // items: товары набора (цена = сумма). Пустой items: набор подбирается индивидуально.
  { id: "c-gut", coached: true, name: "Здоровый кишечник", duration: "5 недель",
    cover: "img/cover-gut.webp", start: "Старт 5 числа каждого месяца", format: "Онлайн, из любой точки мира",
    items: ["probiotic", "protein", "xsmag", "doublex", "liver", "garlic", "omega", "fiber", "appetite"],
    tags: ["gut", "immunity", "shape"],
    desc: "Пошаговая программа для комфортного пищеварения и лёгкости. 5 недель заботы о себе под сопровождением специалистов и врача-эксперта.",
    features: ["Ежедневное сопровождение", "Меню и рекомендации", "Чат поддержки", "Экспертные эфиры", "Разбор анализов", "Рекомендации по нутриентам"],
    forWhom: "При вздутии и дискомфорте, для комфортного пищеварения, для поддержки иммунитета, для тех, кто хочет чувствовать лёгкость каждый день.",
    note: "Количество мест ограничено" },
  { id: "c-detox14", coached: true, name: "Детокс 14 дней", duration: "14 дней",
    cover: "img/cover-detox14.webp", start: "Старт по набору группы", format: "Онлайн, в чате",
    items: [], tags: ["gut", "energy", "shape"],
    desc: "Мягкая программа обновления: больше энергии, лёгкости и баланса. Без строгих диет, без подсчёта калорий, без изнурительных тренировок и без стресса.",
    features: ["14 дней пользы: ежедневные темы и простые объяснения", "Готовое меню на каждый день", "Поддержка и мотивация", "Отчёты в чате и лёгкие задания", "Бонусы: чек-листы, гайды, материалы экспертов"],
    forWhom: "Для тех, кто хочет вернуть энергию, лёгкость и полезные привычки." },
  { id: "c-detox21", coached: true, name: "Детокс 21 день", duration: "21 день",
    cover: "img/cover-detox21.webp", start: "Старт по набору группы", format: "Онлайн, в чате",
    items: ["bdlight"], tags: ["gut", "shape", "energy"],
    desc: "Комплексная программа мягкого очищения и восстановления. Больше энергии, ясности и лёгкости каждый день.",
    features: ["Пошаговый план на 21 день", "Сбалансированное меню и рецепты", "Поддержка и мотивация каждый день", "Чек-листы, гайды и полезные материалы", "Практики для энергии и гармонии", "Рекомендации по образу жизни"],
    forWhom: "Для тех, кто хочет мягко перезагрузиться без стресса для организма." },

  // ---------- Готовые наборы ----------
  { id: "p-energy", benefit: "Три базовых продукта, которых чаще всего не хватает в рационе: витамины и минералы, омега-3 и витамин D. Помогают поддерживать энергию, работу мозга, сердца и иммунитета, когда много работы и мало времени на полноценное питание.",
    name: "Энергия каждый день", duration: "30 дней",
    items: ["daily", "omega", "vitd"], tags: ["energy", "immunity"],
    desc: "Базовый набор для тех, кто устаёт к середине дня. Схема приёма и поддержка консультанта." },
  { id: "p-immunity", benefit: "Поддержка защитных сил с трёх сторон: витамин D и витамин С вносят вклад в работу иммунной системы, а пробиотик поддерживает микрофлору кишечника, где находится большая часть иммунных клеток.",
    name: "Крепкий сезон", duration: "30 дней",
    items: ["vitd", "vitc", "probiotic"], tags: ["immunity", "family"],
    desc: "Поддержка организма в холодное время года." },
  { id: "p-shape", benefit: "Растительный белок даёт сытость и помогает сохранить мышцы, клетчатка поддерживает пищеварение, а витамины закрывают пробелы рациона, пока вы меняете питание. Без голодовок и жёстких диет.",
    name: "Перезагрузка 21 день", duration: "21 день",
    items: ["protein", "fiber", "daily"], tags: ["shape", "energy"],
    desc: "Питание, привычки и ежедневная связь с консультантом. Без жёстких диет." },
  { id: "p-skin", benefit: "Полный ежедневный уход за лицом в три шага: очищение, тоник, увлажняющий крем. Омега-3 поддерживает кожу изнутри. Кожа выглядит увлажнённой, гладкой и сияющей.",
    name: "Сияние кожи", duration: "30 дней",
    items: ["cleanser", "toner", "cream", "omega"], tags: ["skin"],
    desc: "Уход снаружи и поддержка изнутри. Подберём под ваш тип кожи." },
  { id: "p-home", benefit: "Четыре концентрата закрывают всю уборку и стирку. Меньше бутылок и агрессивной химии в доме, заметная экономия денег и места, безопасно для семьи с детьми.",
    name: "Чистый дом", duration: "3-4 месяца",
    items: ["loc", "sa8", "dish", "glass"], tags: ["clean", "family"],
    desc: "Концентраты на всю уборку и стирку. Меньше бутылок, меньше агрессивной химии." },
  { id: "set-immunity", official: true, sku: "316336", fixedKzt: 57247, img: "img/set-immunity.webp",
    name: "Программа «Защита иммунитета»", duration: "курс по схеме",
    items: ["vitc", "vitd", "echinacea", "zinc"], tags: ["immunity", "family"],
    desc: "Официальная программа Nutrilite: 4 продукта для поддержки иммунитета, выгоднее, чем по отдельности.",
    benefit: "Комплексная поддержка защитных сил организма, особенно в холодное время года и в сезон простуд. Витамин С Плюс поддерживает постоянную концентрацию витамина С, витамин D помогает иммунитету работать как следует, эхинацея поддерживает общее самочувствие, а цинк с селеном защищают иммунную систему и заодно помогают коже и волосам." },
  { id: "set-hair", name: "Сильные и гладкие волосы", duration: "уход на 1-2 месяца",
    items: ["shampoo", "conditioner", "hairmask", "hairoil"], tags: ["hair"],
    desc: "Полный уход Satinique: мытьё, кондиционер, восстанавливающая маска и сыворотка-масло для кончиков.",
    benefit: "Волосы становятся гладкими, блестящими и послушными, меньше ломаются и путаются. Шампунь и кондиционер увлажняют и дают гладкость каждый день, маска укрепляет ослабленные и окрашенные волосы, а сыворотка-масло убирает пушистость и восстанавливает секущиеся кончики." },
  { id: "set-body", name: "Уход за телом", duration: "уход на 1-2 месяца",
    items: ["showergel", "bodylotion", "handcream"], tags: ["skin", "family"],
    desc: "Линия g&h с маслом ши, керамидами и маслом чиа: гель для душа, лосьон для тела и крем для рук.",
    benefit: "Мягкое очищение и питание кожи всего тела без сухости и стянутости. Керамиды и масло ши помогают коже удерживать влагу и защищают её барьер, поэтому кожа остаётся гладкой и увлажнённой. Средства без сульфатов, парабенов и спирта, подходят для ежедневного ухода всей семьи." }
];
